문자열 formatting

## %기법

In [29]:
print('9 / 6 = %.3f'%(9/6))

9 / 6 = 1.500


## F-string 기법

In [35]:
print(f'9/6 = {9/6:.1f}')
print(f'9/6 = {9/6:.5f}')
val=9/6
print(f'9/6 = {val:.1f}')
print(f'9/6 = {val:.5f}')

9/6 = 1.5
9/6 = 1.50000
9/6 = 1.5
9/6 = 1.50000


In [36]:
for i in range(1,101):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100


In [43]:
myfile= open('one2hund.txt','w') # file 열기
for i in range(1,101):
  myfile.write(f'{i}\n') # myfile instance의 write method 활용
myfile.close() # file 닫기
!head one2hund.txt

1
2
3
4
5
6
7
8
9
10


In [49]:
myfile= open('one2hund.txt','w') # file 열기
for i in range(1,101):
  myfile.write(f'{i}\n') # myfile instance의 write method 활용
myfile.close() # file 닫기

myfile = open('one2hund.txt','r') # file 열기
cnt=myfile.read()
print(cnt)

1
2
3
4
5
6
7
8
9
10
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100



In [50]:
cnt

'1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59\n60\n61\n62\n63\n64\n65\n66\n67\n68\n69\n70\n71\n72\n73\n74\n75\n76\n77\n78\n79\n80\n81\n82\n83\n84\n85\n86\n87\n88\n89\n90\n91\n92\n93\n94\n95\n96\n97\n98\n99\n100\n'

In [41]:
!head one2hund.txt

123456789101112131415161718192021222324252627282930313233343536373839404142434445464748495051525354555657585960616263646566676869707172737475767778798081828384858687888990919293949596979899100

In [1]:
import numpy as np

In [ ]:
ls ../data/

matrix
matrix_01.csv
matrix_01.csv~
matrix_01.txt
matrix_01.txt~
matrix_02.txt
matrix_03.txt
score_record_2017_MF_final_analysis.txt*


## Numpy

In [ ]:
import numpy as np
print(np.__version__)
print(np.__file__)
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(type(arr))
print(arr.shape)   # (2, 3) → 2행 3열
print(arr.ndim)    # 차원 수 → 2
print(arr.size)    # 전체 원소 개수 → 6
print(arr.dtype)   # 데이터 타입 → int64 (환경에 따라 다름)
print(arr.ravel())  ## memory-efficient
print(arr.flatten()) ## independent copy
print(arr.ravel().sum())
print(arr.flatten().sum())

1.26.4
/Users/youngung/.pyenv/versions/3.12.2/lib/python3.12/site-packages/numpy/__init__.py
<class 'numpy.ndarray'>
(2, 3)
2
6
int64
[1 2 3 4 5 6]
[1 2 3 4 5 6]
21
21


In [115]:
arr.ravel()
arr
arr.flatten()
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
mylist=list(range(101))
mylist
myarray=np.array(mylist)
myarray

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [61]:
%%timeit
s=0.
for i in range(100):
    s=s+mylist[i]
#print(s)

1.85 µs ± 17.2 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [62]:
%%timeit
s=myarray.sum()

539 ns ± 6.63 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [64]:
539/1850

0.2913513513513514

In [ ]:
arr.flatten().sum()

21

# 차원과 축 관점

## 차원

In [70]:
import numpy as np

a = np.array(5)                  # 스칼라 (0차원)
b = np.array([1, 2, 3])          # 벡터 (1차원)
c = np.array([[1, 2, 3],
              [4, 5, 6]])        # 행렬 (2차원)
d = np.array([[[1], [2], [3]],
              [[4], [5], [6]]])  # 3차원 텐서
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:
a=np.arange(100)
a=a.reshape(10,10)
#a[:,::2]
a[0::2,::]
#a[1::2,::]
a[0::3,::]
a[::,1::2]


array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49],
       [51, 53, 55, 57, 59],
       [61, 63, 65, 67, 69],
       [71, 73, 75, 77, 79],
       [81, 83, 85, 87, 89],
       [91, 93, 95, 97, 99]])

In [109]:
a=np.arange(1000)
a=a.reshape(10,10,10)
#a[::5,::,::]
a

array([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
        [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]],

       [[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
        [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
        [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
        [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
        [160, 161, 162, 163, 164, 165,

In [74]:
a = np.arange(15)
print(a)
b=a.reshape(3,5)
b

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [79]:
print(b[0,:])
print(b[1,:])
print(b[2,:])

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]


In [80]:
print(b[:,0])
print(b[:,1])
print(b[:,2])
print(b[:,3])
print(b[:,4])

[ 0  5 10]
[ 1  6 11]
[ 2  7 12]
[ 3  8 13]
[ 4  9 14]


List 의 indexing & slicing

In [ ]:
myList=list((3,4,5,3,10,3,5))
myList[::2]

[3, 5, 10, 5]

In [82]:
myarray=np.array((3,4,5,3,10,3,5))
myarray[2:6:2]

array([ 5, 10])

In [ ]:
print(arr)
#print(arr[1::,1::])
#print(arr[::2,::2])
print(arr[::-1,::-1])
print(arr[::-1,::])
print(arr[::,::-1])

[[1 2 3]
 [4 5 6]]
[[6 5 4]
 [3 2 1]]
[[4 5 6]
 [1 2 3]]
[[3 2 1]
 [6 5 4]]


In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
dotprod=0.
for i in range(len(a)):
    dotprod+=a[i]*b[i]
print(dotprod)
dotprod=(a*b).sum()
print(dotprod)

print(a@b)

32.0
32
32


## Matrix multiplication

In [28]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [1, 3]])

C=[[0,0],[0,0]] # initialization
C[0][0]=A[0,0]*B[0,0]+A[0,1]*B[1,0]
C[0][1]=A[0,0]*B[0,1]+A[0,1]*B[1,1]
C[1][0]=A[1,0]*B[0,0]+A[1,1]*B[1,0]
C[1][1]=A[1,0]*B[0,1]+A[1,1]*B[1,1]
print('1:',C)

1: [[4, 6], [10, 12]]


In [29]:
C=[[0,0],[0,0]]
i=0;j=0
C[i][j]=A[i,0]*B[0,j]+A[i,1]*B[1,j]
i=0;j=1
C[i][j]=A[i,0]*B[0,j]+A[i,1]*B[1,j]
i=1;j=0
C[i][j]=A[i,0]*B[0,j]+A[i,1]*B[1,j]
i=1;j=1
C[i][1]=A[i,0]*B[0,j]+A[i,1]*B[j,1]
print('2:',C)

2: [[4, 6], [10, 12]]
