In [19]:
import numpy as np

In [1]:
A = [[1, 2], [3, 4]]
B = [[2, 0], [1, 3]]

C=[[0,0],[0,0]]
C[0][0]=A[0][0]*B[0][0]+A[0][1]*B[1][0]
C[0][1]=A[0][0]*B[0][1]+A[0][1]*B[1][1]
C[1][0]=A[1][0]*B[0][0]+A[1][1]*B[1][0]
C[1][1]=A[1][0]*B[0][1]+A[1][1]*B[1][1]
print('1:',C)

C=[[0,0],[0,0]]
i=0;j=0
C[i][j]=A[i][0]*B[0][j]+A[i][1]*B[1][j]
i=0;j=1
C[i][j]=A[i][0]*B[0][j]+A[i][1]*B[1][j]
i=1;j=0
C[i][j]=A[i][0]*B[0][j]+A[i][1]*B[1][j]
i=1;j=1
C[i][1]=A[i][0]*B[0][j]+A[i][1]*B[j][1]
print('2:',C)


#따라서...
C=[[0,0],[0,0]]
for i in range(2):
    for j in range(2):
        C[i][j]=A[i][0]*B[0][j]+A[i][1]*B[1][j] ## 네 statements가 동일함에 주목!
print('3:',C)

#더 줄이면?
C=[[0,0],[0,0]]
for i in range(2):
    for j in range(2):
        for k in range(2):
            C[i][j]+=A[i][k]*B[k][j]
print('5:',C)

import numpy as np
print('6:',np.array(A) @ np.array(B))          # 행렬 곱
print('7:',np.dot(A, B))   # 동일


1: [[4, 6], [10, 12]]
2: [[4, 6], [10, 12]]
3: [[4, 6], [10, 12]]
5: [[4, 6], [10, 12]]
6: [[ 4  6]
 [10 12]]
7: [[ 4  6]
 [10 12]]


In [17]:
def get_mag(v):
    import math
    return math.sqrt(v[0]**2+v[1]**2+v[2]**2)

def get_ang(a,b):
    import math
    dotprod=0.
    for i in range(3):
        dotprod+=a[i]*b[i]
    costh=dotprod/(get_mag(a)*get_mag(b))
    print(f'costh:{costh}')
    th=math.acos(costh)
    return th

a=[1,0,0]
b=[0,1,0]
angle=get_ang(a,b)
print('ang in radian:', angle)
## angle to degree?
print('ang in degree:', angle*180/3.141592)

costh:0.0
ang in radian: 1.5707963267948966
ang in degree: 90.00001872397223


Einstein 표기법

In [13]:
import numpy as np
a=np.array([2,3,4])
np.sqrt(np.einsum('i->',a**2))

5.385164807134504

In [14]:
np.linalg.norm(a)

5.385164807134504

Vector 내적

In [21]:
import numpy as np
## Numpy로 구현
a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.einsum('i,i->',a,b))
print(a@b)
print(np.dot(a,b))
print(np.inner(a,b))
print(np.sum(a*b))

32
32
32
32
32


행렬 벡터 곱

In [25]:
A=np.array([[2,1],[3,1]])
v=np.array([3,1])
print(np.einsum('ij,j->i',A,v))
print(A@v)

[ 7 10]
[ 7 10]


## 행렬 곱

In [31]:
import numpy as np
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
B=np.array([[3,2,1],[6,5,4],[9,8,7]])
# 혹은 더 줄여서 (python 3.5이상)
C=A@B # dtype 이 float로 바뀜
print(C)

[[ 42  36  30]
 [ 96  81  66]
 [150 126 102]]


In [ ]:
import numpy as np
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
B=np.array([[3,2,1],[6,5,4],[9,8,7]])
np.einsum('ik,kj->ij',A,B)

array([[ 42,  36,  30],
       [ 96,  81,  66],
       [150, 126, 102]])

이중행렬 곱

In [35]:
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
B=np.array([[3,2,1],[6,5,4],[9,8,7]])
c=0.
for i in range(3): # i is outer
	for j in range(3): # j is inner
	  c+=A[i,j]*B[i,j]
print(c)
c=np.einsum('ij,ij->',A,B)
print(c)

273.0
273
