In [1]:
import numpy as np

In [3]:
ls ../data/

matrix
matrix_01.csv
matrix_01.csv~
matrix_01.txt
matrix_01.txt~
matrix_02.txt
matrix_03.txt
score_record_2017_MF_final_analysis.txt*


## Numpy

In [5]:
import numpy as np
print(np.__version__)
print(np.__file__)
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)   # (2, 3) → 2행 3열
print(arr.ndim)    # 차원 수 → 2
print(arr.size)    # 전체 원소 개수 → 6
print(arr.dtype)   # 데이터 타입 → int64 (환경에 따라 다름)
print(arr.flatten())
print(arr.flatten().sum())

1.26.4
/Users/youngung/.pyenv/versions/3.12.2/lib/python3.12/site-packages/numpy/__init__.py
(2, 3)
2
6
int64
[1 2 3 4 5 6]
21


In [9]:
arr.flatten().sum()

21

In [ ]:
print(arr)
#print(arr[1::,1::])
#print(arr[::2,::2])
print(arr[::-1,::-1])
print(arr[::-1,::])
print(arr[::,::-1])

[[1 2 3]
 [4 5 6]]
[[6 5 4]
 [3 2 1]]
[[4 5 6]
 [1 2 3]]
[[3 2 1]
 [6 5 4]]


In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
dotprod=0.
for i in range(len(a)):
    dotprod+=a[i]*b[i]
print(dotprod)
dotprod=(a*b).sum()
print(dotprod)

print(a@b)

32.0
32
32


## Matrix multiplication

In [28]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [1, 3]])

C=[[0,0],[0,0]] # initialization
C[0][0]=A[0,0]*B[0,0]+A[0,1]*B[1,0]
C[0][1]=A[0,0]*B[0,1]+A[0,1]*B[1,1]
C[1][0]=A[1,0]*B[0,0]+A[1,1]*B[1,0]
C[1][1]=A[1,0]*B[0,1]+A[1,1]*B[1,1]
print('1:',C)

1: [[4, 6], [10, 12]]


In [29]:
C=[[0,0],[0,0]]
i=0;j=0
C[i][j]=A[i,0]*B[0,j]+A[i,1]*B[1,j]
i=0;j=1
C[i][j]=A[i,0]*B[0,j]+A[i,1]*B[1,j]
i=1;j=0
C[i][j]=A[i,0]*B[0,j]+A[i,1]*B[1,j]
i=1;j=1
C[i][1]=A[i,0]*B[0,j]+A[i,1]*B[j,1]
print('2:',C)

2: [[4, 6], [10, 12]]
